[issue/16] - added notifications part
teamulster2/report pull request #29
Opened 2021-09-21 14:54 UTC by diehmlukas

close #16

2021-09-21 15:02 UTC, mac641 requested changes
Just some small improvement suggestions ;)

2021-09-21 15:02 UTC, mac641 commented on report/04_implementation/01_flutter_application.md
> +the study participant can be specifically reminded to use the app. The setting
```suggestion
the study participant can be specifically reminded to use the app. The settings 
```

2021-09-21 15:02 UTC, mac641 commented on report/04_implementation/01_flutter_application.md
> +UTC and the notification text can be set. The heading of each notification is
```suggestion
option can be found in the config, where both the desired notification times 
formatted as UTC and the notification text can be set. The heading of each notification is 
```

2021-09-22 07:09 UTC, AnnaGsell submitted a review, later dismissed

2021-09-22 07:12 UTC, carina-str commented on report/04_implementation/01_flutter_application.md
> +notification is the set study name. Further methods have been implemented which
```suggestion
notification is the study name, which is set in the configuration of the app. Further methods have been implemented which 
```

2021-09-22 07:27 UTC, carina-str approved these changes

2021-09-22 08:06 UTC, treilik approved these changes

2021-09-22 08:06 UTC, treilik commented on report/04_implementation/01_flutter_application.md
> +it possible to make the app more independent of a server.
```suggestion
concept and the privacy and locality of the users data. Instead, the flutter_local_notifications
package was used, which makes it possible to make the app more independent of a server.
```

2021-09-22 08:51 UTC, mac641 approved these changes

2021-09-22 08:56 UTC, merged